import { Take } from '../types';

export const sampleTakes: Take[] = [
  {
    id: '1',
    text: 'Pineapple on pizza is actually delicious and people who hate it are just following a trend',
    category: 'food',
    hotVotes: 1247,
    notVotes: 2103,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    text: 'Working from home is less productive than working in an office',
    category: 'work',
    hotVotes: 892,
    notVotes: 1654,
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    text: 'Cats are better pets than dogs and anyone who disagrees lacks sophistication',
    category: 'pets',
    hotVotes: 2156,
    notVotes: 1843,
    createdAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    text: 'Social media has made society worse, not better',
    category: 'technology',
    hotVotes: 3421,
    notVotes: 987,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    text: 'Money can absolutely buy happiness if you spend it right',
    category: 'life',
    hotVotes: 2876,
    notVotes: 1234,
    createdAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    text: 'Superhero movies are ruining cinema by being too formulaic',
    category: 'entertainment',
    hotVotes: 1543,
    notVotes: 2187,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '7',
    text: 'Climate change is the most important issue of our generation',
    category: 'environment',
    hotVotes: 4123,
    notVotes: 678,
    createdAt: new Date('2024-01-09'),
  },
  {
    id: '8',
    text: 'Meditation is just sitting around doing nothing and people pretend it helps',
    category: 'wellness',
    hotVotes: 567,
    notVotes: 2890,
    createdAt: new Date('2024-01-08'),
  },
  {
    id: '9',
    text: 'Artificial intelligence will replace most jobs within the next 20 years',
    category: 'technology',
    hotVotes: 2345,
    notVotes: 1876,
    createdAt: new Date('2024-01-07'),
  },
  {
    id: '10',
    text: 'Tipping culture has gotten completely out of control',
    category: 'society',
    hotVotes: 3654,
    notVotes: 543,
    createdAt: new Date('2024-01-06'),
  },
];